version: "3"
services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html
    restart: always
    links:
      - db-postgres
  db-postgres:
    image: postgres:12.1
    container_name: db-postgres
    restart: always
    user: 999:999
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qqq
  adminer:
    image: adminer:4.7.5
    ports:
      - "8081:8080"
    links:
      - db-postgres
volumes:
  pgdata:
    driver: local